#!/usr/bin/env python3
"""Inventory pre-V2 refs for non-destructive convergence salvage."""
from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
from collections import Counter

ROOT = pathlib.Path(__file__).resolve().parents[1]
PROCESS_PREFIXES = ("tasks/", "worklog/", "docs/", "prompts/", ".agents/", "sources/")
PROCESS_FILES = {"README.md", "PLAN.md", "FEATURES.md", "ralph.json", "AGENTS.md"}


def git(*args: str, check: bool = True) -> str:
    proc = subprocess.run(["git", *args], cwd=ROOT, text=True, capture_output=True)
    if check and proc.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {proc.stderr.strip()}")
    return proc.stdout.strip()


def is_test_path(path: str) -> bool:
    parts = path.split("/")
    name = parts[-1]
    return (
        path.startswith("tests/")
        or "tests" in parts
        or name.startswith("test_")
        or name.endswith((".test.ts", ".test.tsx", ".spec.ts", ".spec.tsx"))
    )


def is_process_path(path: str) -> bool:
    return path in PROCESS_FILES or path.startswith(PROCESS_PREFIXES)


def is_product_path(path: str) -> bool:
    if path.startswith("crates/"):
        return "/src/" in path or path.endswith(("/src/lib.rs", "/src/main.rs", "Cargo.toml", "build.rs"))
    if path.startswith("web/"):
        return not is_test_path(path) and not path.startswith("web/docs/")
    if path.startswith("scripts/"):
        return True
    return path in {"Cargo.toml", "Cargo.lock", "package.json", "pnpm-lock.yaml"}


def classify(ancestor: bool, paths: list[str]) -> tuple[str, str]:
    if ancestor:
        return "INTEGRATED_ANCESTOR", "none"
    if not paths:
        return "EVIDENCE_ONLY", "heritage-only"
    product = [p for p in paths if is_product_path(p)]
    tests = [p for p in paths if is_test_path(p)]
    process = [p for p in paths if is_process_path(p)]
    if product:
        return "SALVAGE_PRODUCT", "content-review"
    if tests and len(tests) + len(process) == len(paths):
        return "SALVAGE_TEST", "test-review"
    if len(process) == len(paths):
        return "PROCESS_ONLY", "heritage-only"
    return "PENDING_REVIEW", "content-review"


def refs() -> list[str]:
    local = git("for-each-ref", "--format=%(refname:short)", "refs/heads").splitlines()
    remote = git("for-each-ref", "--format=%(refname:short)", "refs/remotes/origin").splitlines()
    return sorted({ref for ref in [*local, *remote] if ref and ref != "origin/HEAD"})


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", default="main-v2")
    parser.add_argument("--json", default="docs/convergence-v2-salvage.json")
    parser.add_argument("--markdown", default="docs/CONVERGENCE_V2_SALVAGE.md")
    args = parser.parse_args()
    base_sha = git("rev-parse", args.base)
    rows = []
    for ref in refs():
        if ref == args.base or ref.startswith("archive/pre-v2/"):
            continue
        head = git("rev-parse", ref)
        ancestor = subprocess.run(
            ["git", "merge-base", "--is-ancestor", head, base_sha],
            cwd=ROOT,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        ).returncode == 0
        merge_base = git("merge-base", base_sha, head, check=False)
        if merge_base:
            paths = git("diff", "--name-only", f"{base_sha}...{head}", check=False).splitlines()
            ahead = int(git("rev-list", "--count", f"{base_sha}..{head}") or "0")
            behind = int(git("rev-list", "--count", f"{head}..{base_sha}") or "0")
        else:
            paths, ahead, behind = [], 0, 0
        disposition, action = classify(ancestor, paths)
        rows.append({
            "ref": ref,
            "head": head,
            "mergeBase": merge_base or None,
            "ahead": ahead,
            "behind": behind,
            "disposition": disposition,
            "recommendedAction": action,
            "changedPaths": paths,
        })
    counts = Counter(row["disposition"] for row in rows)
    payload = {
        "schemaVersion": 1,
        "baseRef": args.base,
        "baseSha": base_sha,
        "counts": dict(sorted(counts.items())),
        "refs": rows,
    }
    json_path = ROOT / args.json
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    md = [
        "# Convergence V2 salvage inventory",
        "",
        f"Base: `{args.base}` / `{base_sha}`",
        "",
        "Generated by `tools/convergence_v2_salvage.py`. Automatic classifications are intake dispositions, not permission to delete any ref.",
        "",
        "## Counts",
        "",
    ]
    for key, value in sorted(counts.items()):
        md.append(f"- `{key}`: {value}")
    md += ["", "## Refs requiring content/test review", ""]
    for row in rows:
        if row["recommendedAction"] in {"content-review", "test-review"}:
            md.append(
                f"- `{row['ref']}` `{row['head'][:12]}` — **{row['disposition']}**; "
                f"ahead {row['ahead']}, behind {row['behind']}, paths {len(row['changedPaths'])}"
            )
    md += [
        "",
        "All other refs remain preserved and are eligible for ancestry-only heritage absorption after useful content is reconciled.",
        "",
    ]
    (ROOT / args.markdown).write_text("\n".join(md), encoding="utf-8")
    print(json.dumps({"base": base_sha, "refs": len(rows), "counts": dict(counts)}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
